[package]
name = "greentic-secrets-wit"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
name = "secrets_wit"
path = "src/lib.rs"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
