[package]
name = "secrets-provider-k8s"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
secrets-core = { path = "../../secrets-core" }
tracing = { workspace = true }
