[package]
name = "secrets-provider-aws-sm"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
anyhow = { workspace = true }
base64 = "0.22.1"
rand = "0.9.2"
serde = { workspace = true }
secrets-core = { path = "../../secrets-core" }
