services:
  localstack:
    image: localstack/localstack:2.3
    container_name: greentic-localstack
    environment:
      - SERVICES=secretsmanager
      - DEBUG=1
    ports:
      - "4566:4566"
    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - --silent
        - http://localhost:4566/_localstack/health
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    volumes:
      - localstack-data:/var/lib/localstack

  azurekv:
    image: ${AZURE_KV_IMAGE:-jamesgoulddev/azure-keyvault-emulator:2.6.6}
    container_name: greentic-azurekv
    ports:
      - "${AZURE_KV_PORT:-8080}:4997"
    environment:
      - Persist=true
    volumes:
      - ${AZURE_KV_CERTS_DIR:-./scripts/azurekv-certs}:/certs
    healthcheck:
      test:
        - CMD-SHELL
        - test -f /certs/emulator.db
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 10s

  vault:
    image: hashicorp/vault:1.15
    container_name: greentic-vault
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
    command: vault server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200
    healthcheck:
      test:
        - CMD
        - vault
        - status
        - -address=http://127.0.0.1:8200
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s

volumes:
  localstack-data:
